# Site settings
author: Lieby Weintraub
title: Sinatra Project 
header-img: img/home-bg.png
email: liebahinda@gmail.com
copyright_name: Lieby Weintraub
description: > # this means to ignore newlines until "baseurl:"
  Recipe App
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  frumgirlwhocodes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
